version: '3'

services:
  api:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
    tty: true
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_PASSWORD: example
      TZ: 'Asia/Tokyo'
    ports: 
      - 5432:5432
  